stages:
- test
- build

test:1.31:
  script: &test_script
  - apt-get update
  - apt-get install -y libz3-dev
  - &print_version rustc --version && cargo --version
  - cargo test --all --all-features --verbose
  image: rust:1.31

test:stable:
  script: *test_script
  image: rust:latest

test:beta:
  script: *test_script
  image: liuchong/rustup:beta

test:nightly:
  script: *test_script
  image: rustlang/rust:nightly

clippy:
  script:
  - *print_version
  - rustup component add clippy
  - cargo clippy --verbose
  image: rust:latest

rustfmt:
  script:
  - *print_version
  - rustup component add rustfmt
  - cargo fmt -- --check
  image: rust:latest

build:
  stage: build
  script:
  - *print_version
  - cargo build --release --verbose
  artifacts:
    paths:
    - target/release/advent-of-code-2018
  image: rustlang/rust:nightly
