[package]
name = "advent-of-code-2018"
version = "0.1.0"
authors = ["Konrad Borowski <konrad@borowski.pw>"]
edition = "2018"

[dependencies]
failure = "0.1.3"
itertools = "0.7.11"
nom = "4.1.1"
regex = "1.1.0"
structopt = "0.2.13"
